name = "biblophilia"
compatibility_date = "2023-03-01"

[[d1_databases]]
binding = "DB"
database_name = "bibliophilia-db"
database_id = "<GET YOUR DB ID>" # Get your databse ID by creating a database (scripts/init_db.sh)
migrations_dir = "drizzle"
